---
# API service version 2

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment-v1
  labels:
    app: payment-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-v1
  template:
    metadata:
      labels:
        app: payment-v1
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/service-meta-version": "1"
        "consul.hashicorp.com/service-tags": "v1"
    spec:
      containers:
      - name: payment
        image: nicholasjackson/broken-service:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: "TRACING_ZIPKIN"
          value: "http://jaeger:9411"

---
# Service to expose payment direct 

apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-v1
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
